repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: [--maxkb=2048]
    -   id: check-merge-conflict

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

-   repo: https://github.com/ambv/black
    rev: 21.6b0
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]

-   repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
    -   id: nbstripout
        args: [--keep-output]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        additional_dependencies: [sqlalchemy-stubs,types-requests]

-   repo: https://github.com/iterative/dvc
    rev: 2.5.0
    hooks:
    -   id: dvc-pre-commit
        language_version: python3
        stages:
        -   commit
    -   id: dvc-pre-push
        additional_dependencies: ['.[all]']
        language_version: python3
        stages:
        -   push
    -   always_run: true
        id: dvc-post-checkout
        language_version: python3
        stages:
        -   post-checkout
